import React, { createContext, useContext, useMemo, useState } from 'react';

const translations = {
  en: {
    'network.online': 'Online',
    'network.offline': 'Offline',
    'loading': 'Loading...',
    'auth.login.title': 'Log in',
    'auth.signup.title': 'Sign up',
    'auth.reset.title': 'Reset password',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.login.submit': 'Log in',
    'auth.signup.submit': 'Create account',
    'auth.reset.submit': 'Send reset link',
    'auth.reset.success': 'Check your inbox for reset instructions.',
    'auth.reset.error': 'Unable to send reset email.',
    'auth.google': 'Continue with Google',
    'auth.forgotPassword': 'Forgot password?',
    'auth.createAccount': 'Create an account',
    'auth.haveAccount': 'Already have an account?',
    'auth.login.link': 'Log in',
    'auth.backToLogin': 'Back to login',
    'auth.logout': 'Log out',
    'home.title': 'My properties',
    'home.subtitle': 'Analyze and monitor the profitability of your buildings.',
    'home.new.button': 'New analysis',
    'home.empty.title': 'No analysis yet',
    'home.empty.description': 'Create your first property analysis to get started.',
    'home.existing.title': 'Saved analyses',
    'home.address.unset': 'Address not specified',
    'home.delete': 'Delete',
    'home.share': 'Share',
    'property.form.title': 'Property information',
    'property.form.simpleMode': 'Simple expenses',
    'property.form.advancedMode': 'Advanced expenses',
    'property.form.save': 'Save analysis',
    'property.form.update': 'Update analysis',
    'property.form.delete.confirm': 'Are you sure you want to delete this property?',
    'property.form.section.basic': 'General information',
    'property.form.section.revenue': 'Revenues',
    'property.form.section.expenses': 'Expenses',
    'property.form.section.financing': 'Financing',
    'property.form.section.acquisition': 'Acquisition costs',
    'property.fields.address': 'Address',
    'property.fields.city': 'City',
    'property.fields.province': 'Province',
    'property.fields.postalCode': 'Postal code',
    'property.fields.askingPrice': 'Asking price',
    'property.fields.purchasePrice': 'Purchase price',
    'property.fields.municipalEvaluation': 'Municipal evaluation',
    'property.fields.numberOfUnits': 'Number of units',
    'property.fields.structureType': 'Structure type',
    'property.fields.annualRent': 'Annual rent',
    'property.fields.parkingRevenue': 'Parking revenue',
    'property.fields.internetRevenue': 'Internet revenue',
    'property.fields.storageRevenue': 'Storage revenue',
    'property.fields.otherRevenue': 'Other revenue',
    'property.fields.vacancyRate': 'Vacancy rate (%)',
    'property.fields.municipalTaxes': 'Municipal taxes',
    'property.fields.schoolTaxes': 'School taxes',
    'property.fields.insurance': 'Insurance',
    'property.fields.electricityHeating': 'Electricity & heating',
    'property.fields.maintenance': 'Maintenance (per unit)',
    'property.fields.concierge': 'Concierge (per unit)',
    'property.fields.managementRate': 'Management rate (%)',
    'property.fields.otherExpenses': 'Other expenses',
    'property.fields.welcomeTax': 'Welcome tax',
    'property.fields.cmhcAnalysis': 'CMHC analysis fees',
    'property.fields.cmhcTax': 'CMHC premium',
    'property.fields.financingType': 'Financing type',
    'property.fields.debtCoverageRatio': 'Debt coverage ratio',
    'property.fields.qualificationRate': 'Qualification rate (%)',
    'property.fields.mortgageRate': 'Mortgage rate (%)',
    'property.fields.amortization': 'Amortization (years)',
    'property.fields.term': 'Term (years)',
    'property.fields.appreciationRate': 'Appreciation rate (%)',
    'property.fields.rentIncreaseRate': 'Rent increase (%)',
    'property.fields.expenseIncreaseRate': 'Expense increase (%)',
    'property.details.title': 'Analysis summary',
    'property.details.revenue': 'Total revenue',
    'property.details.expenses': 'Total expenses',
    'property.details.noi': 'Net operating income',
    'property.details.cashflow': 'Cash flow (year 1)',
    'property.details.capRate': 'Cap rate',
    'property.details.coc': 'Cash-on-cash return',
    'property.details.pricePerDoor': 'Price per door',
    'property.details.debtService': 'Debt service (year 1)',
    'property.details.downPayment': 'Down payment',
    'property.details.ltv': 'Loan-to-value (LTV)',
    'property.details.generateReport': 'Generate report',
    'property.details.years': 'years',
    'back': 'Back',
    'cancel': 'Cancel',
    'save': 'Save',
    'edit': 'Edit',
    'delete': 'Delete',
    'share.link.copied': 'Share link copied to clipboard',
    'share.error': 'Unable to share the analysis',
    'errors.generic': 'Something went wrong. Please try again.'
  },
  fr: {
    'network.online': 'En ligne',
    'network.offline': 'Hors ligne',
    'loading': 'Chargement... ',
    'auth.login.title': 'Connexion',
    'auth.signup.title': 'Inscription',
    'auth.reset.title': 'Réinitialiser le mot de passe',
    'auth.email': 'Courriel',
    'auth.password': 'Mot de passe',
    'auth.login.submit': 'Se connecter',
    'auth.signup.submit': "Créer mon compte",
    'auth.reset.submit': 'Envoyer le lien',
    'auth.reset.success': 'Consultez votre boîte courriel pour les instructions.',
    'auth.reset.error': "Impossible d'envoyer le courriel.",
    'auth.google': 'Continuer avec Google',
    'auth.forgotPassword': 'Mot de passe oublié ?',
    'auth.createAccount': 'Créer un compte',
    'auth.haveAccount': 'Vous avez déjà un compte ?',
    'auth.login.link': 'Se connecter',
    'auth.backToLogin': 'Retour à la connexion',
    'auth.logout': 'Se déconnecter',
    'home.title': 'Mes analyses',
    'home.subtitle': 'Analysez et suivez la rentabilité de vos immeubles.',
    'home.new.button': 'Nouvelle analyse',
    'home.empty.title': "Aucune analyse pour l'instant",
    'home.empty.description': 'Créez votre première analyse pour commencer.',
    'home.existing.title': 'Analyses sauvegardées',
    'home.address.unset': "Adresse non précisée",
    'home.delete': 'Supprimer',
    'home.share': 'Partager',
    'property.form.title': "Informations de l'immeuble",
    'property.form.simpleMode': 'Dépenses simples',
    'property.form.advancedMode': 'Dépenses avancées',
    'property.form.save': "Enregistrer l'analyse",
    'property.form.update': 'Mettre à jour',
    'property.form.delete.confirm': 'Voulez-vous vraiment supprimer cette analyse ?',
    'property.form.section.basic': 'Informations générales',
    'property.form.section.revenue': 'Revenus',
    'property.form.section.expenses': 'Dépenses',
    'property.form.section.financing': 'Financement',
    'property.form.section.acquisition': "Frais d'acquisition",
    'property.fields.address': 'Adresse',
    'property.fields.city': 'Ville',
    'property.fields.province': 'Province',
    'property.fields.postalCode': 'Code postal',
    'property.fields.askingPrice': 'Prix demandé',
    'property.fields.purchasePrice': 'Prix payé',
    'property.fields.municipalEvaluation': 'Évaluation municipale',
    'property.fields.numberOfUnits': "Nombre d'unités",
    'property.fields.structureType': 'Type de structure',
    'property.fields.annualRent': 'Revenus annuels',
    'property.fields.parkingRevenue': 'Revenus de stationnement',
    'property.fields.internetRevenue': 'Revenus Internet',
    'property.fields.storageRevenue': 'Revenus de rangement',
    'property.fields.otherRevenue': 'Autres revenus',
    'property.fields.vacancyRate': 'Taux de vacance (%)',
    'property.fields.municipalTaxes': 'Taxes municipales',
    'property.fields.schoolTaxes': 'Taxes scolaires',
    'property.fields.insurance': 'Assurances',
    'property.fields.electricityHeating': 'Électricité et chauffage',
    'property.fields.maintenance': 'Entretien (par unité)',
    'property.fields.concierge': 'Conciergerie (par unité)',
    'property.fields.managementRate': 'Taux de gestion (%)',
    'property.fields.otherExpenses': 'Autres dépenses',
    'property.fields.welcomeTax': 'Taxe de bienvenue',
    'property.fields.cmhcAnalysis': 'Analyse SCHL',
    'property.fields.cmhcTax': 'Prime SCHL',
    'property.fields.financingType': 'Type de financement',
    'property.fields.debtCoverageRatio': 'Ratio de couverture de la dette',
    'property.fields.qualificationRate': 'Taux de qualification (%)',
    'property.fields.mortgageRate': 'Taux hypothécaire (%)',
    'property.fields.amortization': 'Amortissement (années)',
    'property.fields.term': "Terme (années)",
    'property.fields.appreciationRate': "Appréciation annuelle (%)",
    'property.fields.rentIncreaseRate': 'Hausse des loyers (%)',
    'property.fields.expenseIncreaseRate': 'Hausse des dépenses (%)',
    'property.details.title': 'Sommaire de rentabilité',
    'property.details.revenue': 'Revenus totaux',
    'property.details.expenses': 'Dépenses totales',
    'property.details.noi': 'Revenu net (RNE)',
    'property.details.cashflow': 'Flux de trésorerie (an 1)',
    'property.details.capRate': 'Taux de capitalisation',
    'property.details.coc': 'Rendement cash-on-cash',
    'property.details.pricePerDoor': 'Prix par porte',
    'property.details.debtService': 'Service de la dette (an 1)',
    'property.details.downPayment': 'Mise de fonds',
    'property.details.ltv': 'Ratio prêt-valeur',
    'property.details.generateReport': 'Générer le rapport',
    'property.details.years': 'années',
    'back': 'Retour',
    'cancel': 'Annuler',
    'save': 'Enregistrer',
    'edit': 'Modifier',
    'delete': 'Supprimer',
    'share.link.copied': "Lien de partage copié", 
    'share.error': "Impossible de partager l'analyse",
    'errors.generic': 'Une erreur est survenue. Veuillez réessayer.'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('fr');

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key) => translations[language]?.[key] ?? key,
    availableLanguages: Object.keys(translations)
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
